spring:
  application:
    name: java
  mvc:
    async:
      request-timeout: 300000  # 异步请求超时30秒(单位毫秒)
  profiles:
    include:
      - config
server:
  port: 8001
  connection-timeout: 300s  # 适用于所有Servlet容器
  tomcat:
    connection-timeout: 300000ms  # 连接超时5秒


